[package]
name = "elaine"
version = "1.0.0"
edition = "2024"

[lib]
name = "elaine"
path = "src/lib.rs"

[[bin]]
name = "elaine"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-saphyr = "1.0.0"
schemars = { version = "1.2", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2.5"
clap = { version = "4.6", features = ["derive"] }
anyhow = "1.0"
indicatif = "0.18"
tokio = { version = "1.53", features = ["full"] }
reqwest = { version = "0.13", features = ["json", "stream"] }
futures = "0.3"
axum = "0.7"
tower-http = { version = "0.5", features = ["fs"] }
jsonwebtoken = "9.3"
rust-embed = "8.0"
mime_guess = "2.0"
tempfile = "3.27"
tar = "0.4"
flate2 = "1.1"
regex = "1.13"
toml = "0.8"
axum-extra = { version = "0.9", features = ["query"] }

[build-dependencies]
schemars = { version = "1.2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
